apiVersion: apps/v1
kind: Deployment
metadata:
  name: exobrain-assistant-frontend
  labels:
    app.kubernetes.io/name: exobrain-assistant-frontend
    {{- include "exobrain-stack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.assistantFrontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: exobrain-assistant-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: exobrain-assistant-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.assistantFrontend.image.repository }}:{{ .Values.assistantFrontend.image.tag }}"
          imagePullPolicy: {{ .Values.assistantFrontend.image.pullPolicy }}
          env:
            - name: PUBLIC_LOG_LEVEL
              value: {{ .Values.assistantFrontend.env.PUBLIC_LOG_LEVEL | quote }}
          ports:
            - containerPort: {{ .Values.assistantFrontend.service.port }}
          resources: {{- toYaml .Values.assistantFrontend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: exobrain-assistant-frontend
  labels:
    app.kubernetes.io/name: exobrain-assistant-frontend
    {{- include "exobrain-stack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.assistantFrontend.service.type }}
  selector:
    app.kubernetes.io/name: exobrain-assistant-frontend
  ports:
    - name: http
      port: {{ .Values.assistantFrontend.service.port }}
      targetPort: {{ .Values.assistantFrontend.service.port }}
